### ISSUE TITLE
email and password appear in url

### ISSUE THREAD

**Issue by afischer12** [wealtheffectproject/The-Wealth-Effect#3]
When one enters the email and password and press enter,  the email and password combo appear in the site's url. Perhaps, so another cannot see the email/password combo of another by looking at the url, that info should be encrypted into a code before it appears in the url. It would be harder to incorporate, as it would require both the encryption and decryption code, but it would be much more secure.

**Comment by afischer12** [comment]
It might require the inputs to be encrypted client-side and decrypted server-side, or you can forgo the encryption route and just find a way to keep it from appearing in the url. If you decide to go the encryption route, I'm willing to do the research on the code that would be required both server-side and client-side.

**Comment by wealtheffectproject** [comment]
That's because the form isn't posting the data, it's getting. Don't worry, it's not done.

**Comment by AlexandraIsabel** [comment]
When the code for the login form is completed and actually functions, email and password will be authenticated against a mysql database and there will be separate forms for teachers and students.

**Comment by AlexandraIsabel** [comment]
Work has begun in the shared workspace.

**Comment by afischer12** [comment]
ok thx

**Comment by afischer12** [comment]
Thanks
